#include <stdio.h>
/**
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13,
21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose
values do not exceed four million, find the sum of the even-valued terms.
*/

// is even returns 1
// its not return 0
int isEven(int value) { return !(value % 2); }

int main() {
  int max = 4000000;
  int startFibo = 1;
  int secondFibo = 2;
  int intermediary;
  int sum = 2;
  while (secondFibo < max) {
    intermediary = secondFibo;
    secondFibo += startFibo;
    startFibo = intermediary;
    if (isEven(secondFibo)) {
      sum += secondFibo;
    } else {
      continue;
    }
  }
  printf("result %d", sum);
  return 0;
}
